#!/bin/bash

# Set the current working directory
current_dir=$(pwd)

# Set the parent directory path
parent_dir=$(dirname "$current_dir")

# Loop through all HTML files in the current working directory
for file in *.html; do
    # Check if the file exists in the parent directory and if it's newer
    if [ -e "$parent_dir/$file" ] && [ "$file" -nt "$parent_dir/$file" ]; then
        echo "Copying $file to $parent_dir/$file"
        cp "$file" "$parent_dir/$file"
    elif [ ! -e "$parent_dir/$file" ]; then
        echo "Copying $file to $parent_dir/$file"
        cp "$file" "$parent_dir/$file"
    fi
done






